#server configuration
server:
    host: 0.0.0.0
    port: 8080
    tls: true
    serverCert: certs/server.crt
    serverKey: certs/server.key
#hsm configuration
hsm:
    ip: 192.168.1.1
    port: 2500
    tls: true
    clientCert: certs/hsmclient.pem
    clientKey: certs/hsmclient.key