#server configuration
server:
    host: 0.0.0.0
    port: 8080
    tls: true
    servercert: "server.crt"
    serverkey: "server.key"
#hsm configuration
hsm:
    ip: 192.168.1.1
    port: 2500
    portvariant: 2500
    portkeyblock: 2502
    tls: true
    clientcert: certs/client.pem
    clientkey: certs/client.key